language: android
android:
  components:
    - tools
    - platform-tools
    - android-25
    - tools
    - build-tools-25.0.0

jdk: oraclejdk8
before_install:
  - chmod +x gradlew

# Extend compile timeout to 30 minutes; gwt easily takes 10+.
script: travis_wait 30 ./gradlew clean build