language: android
android:
  components:
    - tools
    - platform-tools
    - android-27
    - tools
    - build-tools-27.0.3
licenses:
    - 'android-sdk-license-.+'
jdk: oraclejdk8
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-27"

# Extend compile timeout to 30 minutes; gwt easily takes 10+.
script: travis_wait 30 ./gradlew clean assembleQa